version: '3.9'
services:
    api:
        container_name: api_f-discover_dev
        image: api_f-discover_dev:latest
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        volumes:
            - ./:/app/